package ind.xwm.thermal.dao;

import ind.xwm.thermal.model.OrderID;

public interface OrderIDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int insert(OrderID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int insertSelective(OrderID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    OrderID selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int updateByPrimaryKeySelective(OrderID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int updateByPrimaryKey(OrderID record);
}