package ind.xwm.thermal.dao;

import ind.xwm.thermal.model.Product;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ProductMapper {

    @Select("select * from Product")
    List<Product> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Product
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Product
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Product
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Product
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Product
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Product
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int updateByPrimaryKey(Product record);
}