package ind.xwm.thermal.dao;

import ind.xwm.thermal.enums.DeliverStatus;
import ind.xwm.thermal.enums.PayStatus;
import ind.xwm.thermal.enums.PrintStatus;
import ind.xwm.thermal.model.ProductOrder;
import org.apache.ibatis.annotations.Many;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ProductOrderMapper {
    @Select("select count(1) from ProductOrder where ORDER_ID = #{orderId}")
    int exist(ProductOrder order);

    @Select("select * from ProductOrder")
    @Results({
            @Result(id = true, column = "ORDER_ID", property = "orderId", jdbcType = JdbcType.VARCHAR),
            @Result(column = "CUSTOMER_NAME", property = "customerName", jdbcType = JdbcType.VARCHAR),
            @Result(column = "CUSTOMER_PHONE", property = "customerPhone", jdbcType = JdbcType.VARCHAR),
            @Result(column = "DELIVER_STATUS", property = "deliverStatus", jdbcType = JdbcType.TINYINT, javaType = DeliverStatus.class),
            @Result(column = "DELIVER_TIME", property = "deliverTime", jdbcType = JdbcType.VARCHAR),
            @Result(column = "ORDER_TIME", property = "orderTime", jdbcType = JdbcType.VARCHAR),
            @Result(column = "PAY_STATUS", property = "payStatus", jdbcType = JdbcType.TINYINT, javaType = PayStatus.class),
            @Result(column = "PRINT_STATUS", property = "printStatus", jdbcType = JdbcType.TINYINT, javaType = PrintStatus.class),
            @Result(column = "TOTAL_COUNT", property = "totalCount", jdbcType = JdbcType.VARCHAR),
            @Result(column = "TOTAL_PRICE", property = "totalPrice", jdbcType = JdbcType.VARCHAR),
            @Result(column = "ORDER_ID", property = "orderDetails", many = @Many(
                    select = "ind.xwm.thermal.dao.OrderDetailMapper.selectByOrderId"))
    })
    List<ProductOrder> findAll();

    @Select("select * from ProductOrder where ORDER_ID = #{orderId}")
    @Results({
            @Result(id = true, column = "ORDER_ID", property = "orderId", jdbcType = JdbcType.VARCHAR),
            @Result(column = "CUSTOMER_NAME", property = "customerName", jdbcType = JdbcType.VARCHAR),
            @Result(column = "CUSTOMER_PHONE", property = "customerPhone", jdbcType = JdbcType.VARCHAR),
            @Result(column = "DELIVER_STATUS", property = "deliverStatus", jdbcType = JdbcType.TINYINT, javaType = DeliverStatus.class),
            @Result(column = "DELIVER_TIME", property = "deliverTime", jdbcType = JdbcType.VARCHAR),
            @Result(column = "ORDER_TIME", property = "orderTime", jdbcType = JdbcType.VARCHAR),
            @Result(column = "PAY_STATUS", property = "payStatus", jdbcType = JdbcType.TINYINT, javaType = PayStatus.class),
            @Result(column = "PRINT_STATUS", property = "printStatus", jdbcType = JdbcType.TINYINT, javaType = PrintStatus.class),
            @Result(column = "TOTAL_COUNT", property = "totalCount", jdbcType = JdbcType.VARCHAR),
            @Result(column = "TOTAL_PRICE", property = "totalPrice", jdbcType = JdbcType.VARCHAR),
            @Result(column = "ORDER_ID", property = "orderDetails", many = @Many(
                    select = "ind.xwm.thermal.dao.OrderDetailMapper.selectByOrderId"))
    })
    ProductOrder findDetail(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ProductOrder
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ProductOrder
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int insert(ProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ProductOrder
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int insertSelective(ProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ProductOrder
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    ProductOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ProductOrder
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int updateByPrimaryKeySelective(ProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ProductOrder
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    int updateByPrimaryKey(ProductOrder record);
}