package ind.xwm.thermal.dao;

import ind.xwm.thermal.model.Unit;

public interface UnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int insert(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int insertSelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    Unit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int updateByPrimaryKeySelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    int updateByPrimaryKey(Unit record);
}