package ind.xwm.thermal.model;

public class OrderID {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderId.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderId.ORDER_ID
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderId.STATUS
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderId.id
     *
     * @return the value of OrderId.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderId.id
     *
     * @param id the value for OrderId.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderId.ORDER_ID
     *
     * @return the value of OrderId.ORDER_ID
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderId.ORDER_ID
     *
     * @param orderId the value for OrderId.ORDER_ID
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderId.STATUS
     *
     * @return the value of OrderId.STATUS
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderId.STATUS
     *
     * @param status the value for OrderId.STATUS
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}