package ind.xwm.thermal.model;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetail.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetail.AMOUNT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetail.PRODUCT_COUNT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetail.PRODUCT_NAME
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetail.PRODUCT_PRICE
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetail.PRODUCT_UNIT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String productUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetail.ORDER_ID
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetail.id
     *
     * @return the value of OrderDetail.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetail.id
     *
     * @param id the value for OrderDetail.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetail.AMOUNT
     *
     * @return the value of OrderDetail.AMOUNT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetail.AMOUNT
     *
     * @param amount the value for OrderDetail.AMOUNT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetail.PRODUCT_COUNT
     *
     * @return the value of OrderDetail.PRODUCT_COUNT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetail.PRODUCT_COUNT
     *
     * @param productCount the value for OrderDetail.PRODUCT_COUNT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setProductCount(String productCount) {
        this.productCount = productCount == null ? null : productCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetail.PRODUCT_NAME
     *
     * @return the value of OrderDetail.PRODUCT_NAME
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetail.PRODUCT_NAME
     *
     * @param productName the value for OrderDetail.PRODUCT_NAME
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetail.PRODUCT_PRICE
     *
     * @return the value of OrderDetail.PRODUCT_PRICE
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetail.PRODUCT_PRICE
     *
     * @param productPrice the value for OrderDetail.PRODUCT_PRICE
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setProductPrice(String productPrice) {
        this.productPrice = productPrice == null ? null : productPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetail.PRODUCT_UNIT
     *
     * @return the value of OrderDetail.PRODUCT_UNIT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getProductUnit() {
        return productUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetail.PRODUCT_UNIT
     *
     * @param productUnit the value for OrderDetail.PRODUCT_UNIT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setProductUnit(String productUnit) {
        this.productUnit = productUnit == null ? null : productUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetail.ORDER_ID
     *
     * @return the value of OrderDetail.ORDER_ID
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetail.ORDER_ID
     *
     * @param orderId the value for OrderDetail.ORDER_ID
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }
}