package ind.xwm.thermal.model;

public class OrderID {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderid.id
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderid.ORDER_ID
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderid.STATUS
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderid.id
     *
     * @return the value of orderid.id
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderid.id
     *
     * @param id the value for orderid.id
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderid.ORDER_ID
     *
     * @return the value of orderid.ORDER_ID
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderid.ORDER_ID
     *
     * @param orderId the value for orderid.ORDER_ID
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderid.STATUS
     *
     * @return the value of orderid.STATUS
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderid.STATUS
     *
     * @param status the value for orderid.STATUS
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}