package ind.xwm.thermal.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Product.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Product.NAME
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Product.PRICE
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Product.UNIT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Product.id
     *
     * @return the value of Product.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Product.id
     *
     * @param id the value for Product.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Product.NAME
     *
     * @return the value of Product.NAME
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Product.NAME
     *
     * @param name the value for Product.NAME
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Product.PRICE
     *
     * @return the value of Product.PRICE
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Product.PRICE
     *
     * @param price the value for Product.PRICE
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Product.UNIT
     *
     * @return the value of Product.UNIT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Product.UNIT
     *
     * @param unit the value for Product.UNIT
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}