package ind.xwm.thermal.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.NAME
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRICE
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.UNIT
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.NAME
     *
     * @return the value of product.NAME
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.NAME
     *
     * @param name the value for product.NAME
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRICE
     *
     * @return the value of product.PRICE
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRICE
     *
     * @param price the value for product.PRICE
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.UNIT
     *
     * @return the value of product.UNIT
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.UNIT
     *
     * @param unit the value for product.UNIT
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}