package ind.xwm.thermal.model;

public class Unit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit.NAME
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit.id
     *
     * @return the value of Unit.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit.id
     *
     * @param id the value for Unit.id
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit.NAME
     *
     * @return the value of Unit.NAME
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit.NAME
     *
     * @param name the value for Unit.NAME
     *
     * @mbg.generated Sat Mar 17 11:38:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}