package ind.xwm.thermal.model;

public class Unit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.id
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.NAME
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.id
     *
     * @return the value of unit.id
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.id
     *
     * @param id the value for unit.id
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.NAME
     *
     * @return the value of unit.NAME
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.NAME
     *
     * @param name the value for unit.NAME
     *
     * @mbg.generated Mon Mar 12 15:41:29 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}